[package]
name = "videocall-suffler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
imgui = "0.9.0"
imgui-winit-support = "0.9.0"
imgui-glium-renderer = "0.9.0"
glium = "0.32.1"
clipboard = "0.5.0"
textwrap = "0.16"

